name: Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "28abf86a-7e4e-4dc1-a169-43631f3f6013"
          heroku_app_name: "drkeddo"
          heroku_email: "arctixmyboy@proton.me"
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          HD_OWNER_ID: "1881720028"
          HD_TELEGRAM_API: "7685644"
          HD_TELEGRAM_HASH: "a713f30f5a21716e6bff334e8ac19b17"
          HD_DATABASE_URL: "mongodb+srv://a1:a1@updated.nkgdabw.mongodb.net/?retryWrites=true&w=majority"
          HD_BOT_TOKEN: "6441621677:AAHEqs7MCVN7u-zgQFf_-bB7L2v08zGN9wI"
          HD_SUDO_USERS: "1881720028"
          HD_UPSTREAM_BRANCH: "main"
          HD_UPSTREAM_REPO: "https://github.com/Sibu07/hk-updated"
          HD_BASE_URL: "https://drkeddo-5990e3275277.herokuapp.com/"
          HD_SEARCH_API_LINK: "https://torrent-api-py-nx0x.onrender.com"
          
